### ISSUE TITLE
Discord link outdated

### ISSUE THREAD

**Issue by Lulalaby** [Unofficial-Devry-IT/DevryCommunity#26]
The discord link in the README is outdated ;)

**Comment by tyates2020** [comment]
Yes, they removed all invites and I don't think he's maintaining this anymore.

**Comment by Lulalaby** [comment]
Oh it's a hub :/

**Comment by tyates2020** [comment]
It was previously just one server, then when they released the hub some changes happen and everyone begin sharing the hub invite instead of the direct server links. If you join, be sure to hit me up.

**Comment by tyates2020** [comment]
You might need to close your issue, the owner isn't monitoring this anymore.

**Comment by Lulalaby** [comment]
> It was previously just one server, then when they released the hub some changes happen and everyone begin sharing the hub invite instead of the direct server links. If you join, be sure to hit me up. 

I can't join badly.
I don't have a mail for that 😅

**Comment by tyates2020** [comment]
You can't get through the hub without a verified email. Here is a direct link https://discord.gg/uuBWr6EUp3, I also hang around Hak5.org's discord as well. Lots of good information is shared there also.
